### Get All Videos
GET http://localhost:8080/api/v1/mini-search/video

### Get Single Video
GET http://localhost:8080/api/v1/mini-search/video/7

### Pagination, Get All Videos
GET http://localhost:8080/api/v1/mini-search/video?page=0&size=2

### Add new Video
POST http://localhost:8080/api/v1/mini-search/video
Content-Type: application/json

{
  "title": "kelantan video",
  "description": "this is a cat video",
  "tags": ["cat", "animals", "video"],
  "uploaderId": 4,
  "uploadDate": "2025-12-16T05:40:41"
}

### Delete Single Video
DELETE http://localhost:8080/api/v1/mini-search/video/1

### Update Video
PUT http://localhost:8080/api/v1/mini-search/video/2
Content-Type: application/json

{
  "title": "Updated Video",
  "description": "This is an updated video",
  "tags": [],
  "uploaderId": 4,
  "uploadDate": "2025-12-16T05:40:41"
}

### Search Video
GET http://localhost:8080/api/v1/mini-search/search?query=video&sortBy=uploadDate
